### ISSUE TITLE
Request - Vault

### ISSUE THREAD

**Issue by DeJayDevelopment** [Turqmelon/MelonEco#1]
Hi Turq. I'm DeJayGmg from Discord. I totally pushed this off. I need a hook with Vault for this plugin to reach into Gringotts pockets and grab the player balance from that. Turning it into the default currency on MelonEco titled Coins. The reason this being is the idea of turning coins (a physical currency easily stealable) into a digital currency called "Tokens" after having say two stacks of coins you can make tokens which will be used to trade for items to roll for many rewards. Unless there is a better way of doing it.

Thank you
~DeJay

**Comment by Turqmelon** [comment]
This sounds like a very specific feature request as opposed to one that could benefit the majority of users. I recommend having a developer hook into the MelonEco API and build this feature for you specifically. Documentation is available on the readme file (repo homepage).

**Comment by DeJayDevelopment** [comment]
I'll try my hand at it then. Thanks.
